DROP SCHEMA IF EXISTS sql_mastery CASCADE;
CREATE SCHEMA sql_mastery;
SET search_path TO sql_mastery;

CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded');
CREATE TYPE payment_status AS ENUM ('pending', 'successful', 'failed', 'refunded');
CREATE TYPE ticket_status AS ENUM ('open', 'pending_customer', 'resolved', 'closed');
CREATE TYPE subscription_status AS ENUM ('trialing', 'active', 'paused', 'cancelled', 'expired');

CREATE TABLE departments (
    department_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name text NOT NULL UNIQUE
);

CREATE TABLE employees (
    employee_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    department_id integer REFERENCES departments(department_id),
    manager_id integer REFERENCES employees(employee_id),
    role_title text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    hired_on date NOT NULL
);

CREATE TABLE customers (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    phone text,
    city text NOT NULL,
    state text,
    country text NOT NULL DEFAULT 'US',
    signup_date date NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CHECK (position('@' in email) > 1)
);

CREATE TABLE products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku text NOT NULL UNIQUE,
    product_name text NOT NULL,
    category text NOT NULL,
    list_price numeric(10, 2) NOT NULL CHECK (list_price >= 0),
    active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE marketing_campaigns (
    campaign_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code text NOT NULL UNIQUE,
    campaign_name text NOT NULL,
    channel text NOT NULL,
    started_on date NOT NULL,
    ended_on date,
    budget numeric(12, 2) NOT NULL CHECK (budget >= 0)
);

CREATE TABLE orders (
    order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers(customer_id),
    sales_rep_id integer REFERENCES employees(employee_id),
    order_date timestamp NOT NULL,
    status order_status NOT NULL,
    channel text NOT NULL,
    coupon_code text,
    shipping_city text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    order_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES products(product_id),
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
    discount_pct numeric(5, 2) NOT NULL DEFAULT 0 CHECK (discount_pct >= 0 AND discount_pct <= 100)
);

CREATE TABLE payments (
    payment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES orders(order_id),
    payment_date timestamp NOT NULL,
    amount numeric(12, 2) NOT NULL,
    method text NOT NULL,
    status payment_status NOT NULL,
    transaction_ref text UNIQUE
);

CREATE TABLE shipments (
    shipment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES orders(order_id),
    shipped_at timestamp,
    delivered_at timestamp,
    carrier text NOT NULL,
    tracking_code text UNIQUE,
    shipping_cost numeric(10, 2) NOT NULL DEFAULT 0,
    CHECK (delivered_at IS NULL OR shipped_at IS NULL OR delivered_at >= shipped_at)
);

CREATE TABLE inventory_movements (
    movement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products(product_id),
    movement_type text NOT NULL CHECK (movement_type IN ('purchase', 'sale', 'return', 'adjustment')),
    quantity_delta integer NOT NULL,
    movement_at timestamp NOT NULL,
    reference text
);

CREATE TABLE support_tickets (
    ticket_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers(customer_id),
    order_id integer REFERENCES orders(order_id),
    assigned_to integer REFERENCES employees(employee_id),
    opened_at timestamp NOT NULL,
    closed_at timestamp,
    priority text NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    status ticket_status NOT NULL,
    subject text NOT NULL
);

CREATE TABLE ticket_events (
    ticket_event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id integer NOT NULL REFERENCES support_tickets(ticket_id) ON DELETE CASCADE,
    event_at timestamp NOT NULL,
    actor_type text NOT NULL CHECK (actor_type IN ('customer', 'agent', 'system')),
    event_type text NOT NULL,
    note text
);

CREATE TABLE web_events (
    event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer REFERENCES customers(customer_id),
    session_id text NOT NULL,
    occurred_at timestamp NOT NULL,
    event_type text NOT NULL,
    page_url text NOT NULL,
    utm_campaign text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE subscriptions (
    subscription_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers(customer_id),
    plan_name text NOT NULL,
    started_on date NOT NULL,
    ended_on date,
    monthly_price numeric(10, 2) NOT NULL CHECK (monthly_price >= 0),
    status subscription_status NOT NULL,
    CHECK (ended_on IS NULL OR ended_on >= started_on)
);

CREATE INDEX idx_customers_email ON customers(email);
CREATE INDEX idx_orders_customer_date ON orders(customer_id, order_date DESC);
CREATE INDEX idx_order_items_order_product ON order_items(order_id, product_id);
CREATE INDEX idx_payments_order_status ON payments(order_id, status);
CREATE INDEX idx_tickets_status_priority ON support_tickets(status, priority);
CREATE INDEX idx_web_events_session_time ON web_events(session_id, occurred_at);
CREATE INDEX idx_web_events_metadata_gin ON web_events USING GIN (metadata);
