flowchart LR
    %% LEFT
    subgraph C1[Clients]
        direction TB
        CLIENT[Web / Mobile User]
    end

    %% GATEWAY
    subgraph C2[Gateways]
        direction TB
        APIGW[API Gateway]
    end

    %% SERVICES
    subgraph C3[Services]
        direction TB
        USVC[User Service]
        FUNDS[Funds Service]
    end

    %% DATABASES
    subgraph C4[Databases]
        direction TB
        UDB[(User DB)]
        FDB[(Funds DB)]
    end

    %% EXTERNAL
    subgraph C5[External Systems]
        direction TB
        KYC[KYC Provider]
        BANK[Payment Gateway / Bank]
    end

    CLIENT -->|signup / login / add funds| APIGW
    APIGW -->|user onboarding| USVC
    APIGW -->|add / withdraw money| FUNDS

    USVC -->|store profile + KYC status| UDB
    USVC -->|verify identity| KYC

    FUNDS -->|store ledger / balance| FDB
    FUNDS -->|move money| BANK

    classDef svc fill:#ffffff,stroke:#111,stroke-width:2px,color:#111;
    classDef db fill:#ffffff,stroke:#111,stroke-width:1.5px,color:#111;
    classDef ext fill:#fafafa,stroke:#111,stroke-width:2px,color:#111;
    classDef gw fill:#f3f3f3,stroke:#111,stroke-width:2.5px,color:#111;

    class APIGW gw;
    class USVC,FUNDS svc;
    class UDB,FDB db;
    class KYC,BANK ext;